### ISSUE TITLE
Incorrect handling of optional fields may cause rejection of valid reports

### ISSUE THREAD

**Issue by JasonVranek** [PufferFinance/rave#13]
Similar to [[Valid reports with status OK will always be rejected](https://www.notion.so/Valid-reports-with-status-OK-will-always-be-rejected-443a5219898a414984e02fdb6ae9478a?pvs=21)](https://www.notion.so/Valid-reports-with-status-OK-will-always-be-rejected-443a5219898a414984e02fdb6ae9478a?pvs=21), the `buildJSON()` function does not correctly handle optional fields that may or may not be present under certain conditions. This may cause valid reports to be rejected. Below are a few examples according to the [[Intel Attestation Service API Documentation](https://api.trustedservices.intel.com/documents/sgx-attestation-api-spec.pdf)](https://api.trustedservices.intel.com/documents/sgx-attestation-api-spec.pdf). Note that `_verifyReportContents()` only allows reports with status `OK` or `SW_HARDENING_NEEDED`, so we only discuss the examples with relation to those two statuses.

- `epidPseudonym` is always present in the reconstructed JSON, but it is only present in the actual JSON if the `isvEnclaveQuoteBody` has the `SIGNATURE_TYPE` bit set to 1 (linkable EPID signature).
    
    > Lines in `buildJSON()` where `epidPseudonym` is unconditionally included
    > 
    > 
    > ```solidity
    > function buildJSON(Values memory values) public pure returns (string memory json) {
    >     json = string(
    >         abi.encodePacked(
    >             '{"id":"',
    >             values.id,
    >             '","timestamp":"',
    >             values.timestamp,
    >             '","version":',
    >             values.version,
    >             ',"epidPseudonym":"',
    >             values.epidPseudonym
    >         )
    >     );
    > ```
    > 
- `pseManifestStatus` and `pseManifestHash` are optional fields that will be present in the actual report if the original attestation evidence payload has a `pseManifest` field. In particular, `pseManifestStatus` will only be included if `isvEnclaveQuoteStatus` is also set to `OK` or `SW_HARDENING_NEEDED`. However, `buildJSON()` does not include these fields if they exist.
- `platformInfoBlob` is an optional field that may be included if `pseManifestStatus` is set to `OUT_OF_DATE`, `REVOKED`, or `RL_VERSION_MISMATCH`.
- `nonce` is an optional field that will be present in the actual report if and only if the original attestation evidence payload also provides a `nonce`.

## Impact

The reconstructed report will be different from the actual report due to the extra optional fields. Thus, the signature verification will almost certainly fail as the SHA-256 digest of the reconstructed report will be different from that of the actual report.

## Recommendation

The developers should extend `buildJSON()` to handle the above cases, and they should carefully read the Intel Attestation Service API documentation to ensure that all fields that may be present in a report whose status is accepted by RAVe (`OK` and `SW_HARDENING_NEEDED`) are correctly handled.

**Comment by robertsdotpm** [comment]
Added an if statement to check for this. JSON schema also validates this now.
