### ISSUE TITLE
Valid reports with status OK will always be rejected

### ISSUE THREAD

**Issue by JasonVranek** [PufferFinance/rave#14]
In order to verify the signature on a report returned by Intel’s Attestation Service, the RAVe smart contracts will be provided with (1) an ABI-encoded representation of the fields of the attestation report JSON object; (2) the cryptographic signature of the report; (3) the ASN.1 DER-encoded X.509 leaf certificate; and (4) some other parameters. The signature will be verified by reconstructing the original JSON object and then checking the signature against the reconstructed JSON and the certificate.  

Specifically, the fields of the report will be decoded into a `Values` struct, which will then be passed into the `buildJSON()` method to reconstruct the JSON report from the fields listed in `Values`. Currently, the logic will unconditionally include the `advisoryURL` and `advisoryIDs` in the reconstructed JSON. This will be inconsistent with the actual report when the `isvEnclaveQuoteStatus` is `OK`, as the `advisoryURL` and `advisoryIDs` fields will be omitted from the actual report.

> Relevant lines in `buildJSON()`
> 
> 
> ```solidity
> function buildJSON(Values memory values) public pure returns (string memory json) {
>     json = string(/*...*/);
>     json = string(
>         abi.encodePacked(
>             json,
>             '","advisoryURL":"',
>             values.advisoryURL,
>             '","advisoryIDs":',
>             values.advisoryIDs,
>             ',"isvEnclaveQuoteStatus":"',
>             values.isvEnclaveQuoteStatus,
>             '","isvEnclaveQuoteBody":"',
>             values.isvEnclaveQuoteBody,
>             '"}'
>         )
>     );
> }
> ```
> 

## Impact

The reconstructed report will always be different from the actual report due to the extra `advisoryURL` and `advisoryIDs` fields. Thus, the signature verification will almost certainly fail as the SHA-256 digest of the reconstructed report will be different from that of the actual report. This may incentivize users to worsen their security status to `SW_HARDENING_NEEDED` in order to pass RAVe’s verification logic.

## Recommendation

The reconstructed report should only include `advisoryURL` and `advisoryIDs` when the status matches one of the prerequisite statuses indicated in the Intel Attestation Service documentation.

**Comment by robertsdotpm** [comment]
Now only including these fields when SW_HARDENED is set.
