### ISSUE TITLE
BadReportSignature error thrown if reconstructed JSON is inconsistent, but signature is valid

### ISSUE THREAD

**Issue by JasonVranek** [PufferFinance/rave#19]
If the reconstructed JSON contains extra keys or is missing keys that should otherwise be in the report, then `verifyRemoteAttestation()` will throw a `BadReportSignature` error even though the cause is likely due to the JSON reconstruction or status, not due to the signature verification failing.

> Relevant lines in `verifyRemoteAttestation()`
> 
> 
> ```solidity
> // Decode the encoded report JSON values to a Values struct and reconstruct the original JSON string
> (Values memory reportValues, bytes memory reportBytes) = _buildReportBytes(report);
> 
> // Verify the report was signed by the SigningPK
> if (!verifyReportSignature(reportBytes, sig, signingMod, signingExp)) {
>     revert BadReportSignature();
> }
> 
> // Verify the report's contents match the expected
> payload = _verifyReportContents(reportValues, mrenclave, mrsigner);
> ```
> 

## Impact

If there is an issue in reconstructing the JSON, the error message will be a “false positive” in that it identifies the issue incorrectly. This can cause developers or users to waste time investigating a supposed signature error when in fact the problem lies with key handling in the report.

## Recommendation

To clarify the error, the call to `_verifyReportContents()` can be moved above the call to `verifyReportSignature()`. Since the former checks the `isvEnclaveQuoteStatus` (which then will make some fields optional or mandatory), this will aid debugging by making the error reporting more accurate.

**Comment by robertsdotpm** [comment]
This is true but the API itself is consistent so will close this for now.
