### ISSUE TITLE
readNodeLength does not handle length 0 nodes correctly

### ISSUE THREAD

**Issue by JasonVranek** [PufferFinance/rave#22]
The function `readNodeLength()` parses an ASN.1 DER data value (see [[ITU-T Rec. X.690](https://www.itu.int/ITU-T/studygroups/com17/languages/X.690-0207.pdf)](https://www.itu.int/ITU-T/studygroups/com17/languages/X.690-0207.pdf)) at a given index `ix` in the raw DER data in order to build a packed “pointer” data structure to the data value starting at `ix`. To build this pointer, `readNodeLength()` must parse the length octets representing the number of bytes of the contents octets. 

The length has one of two forms. The short form consists of a single byte with the highest bit set to 1 (corresponding to the then-branch), with the other bits storing the length; and the long form consists of an initial byte that indicates the number of subsequent bytes will store the actual length. In either case, the length will then be used to calculate the starting and ending indices of the contents octets (`ixFirstContentByte` and `ixLastContentByte`). Lastly, the packed pointer will be constructed by a call to `NodePtr.getPtr()`.

> Definition of `readNodeLength`
> 
> 
> ```solidity
> function readNodeLength(bytes memory der, uint256 ix) private pure returns (uint256) {
>     uint256 length;
>     uint80 ixFirstContentByte;
>     uint80 ixLastContentByte;
>     if ((der[ix + 1] & 0x80) == 0) {
>         length = uint8(der[ix + 1]);
>         ixFirstContentByte = uint80(ix + 2);
>         ixLastContentByte = uint80(ixFirstContentByte + length - 1);
>     } else {
>         uint8 lengthbytesLength = uint8(der[ix + 1] & 0x7F);
>         if (lengthbytesLength == 1) {
>             length = der.readUint8(ix + 2);
>         } else if (lengthbytesLength == 2) {
>             length = der.readUint16(ix + 2);
>         } else {
>             length = uint256(der.readBytesN(ix + 2, lengthbytesLength) >> (32 - lengthbytesLength) * 8);
>         }
>         ixFirstContentByte = uint80(ix + 2 + lengthbytesLength);
>         ixLastContentByte = uint80(ixFirstContentByte + length - 1);
>     }
>     return NodePtr.getPtr(ix, ixFirstContentByte, ixLastContentByte);
> }
> ```
> 

However, it appears that all functions related to `NodePtr` assumes that the range starting at `ixFirstContentByte` and ending at `ixLastContentByte` is inclusive on both ends, i.e. that the length is always greater than zero. There is no validation in `readNodeLength()` that the length is nonzero; and in fact, a length of zero is allowed in actual DER, as stated by section 8.1.3.4 of ITU-T Rec. X.690:

> In the short form, the length octets shall consist of a single octet in which bit 8 is zero and bits 7 to 1 encode the number of octets in the contents octets (which may be zero)
> 

## Impact

If there is a data value with a length of zero, then `ixLastContentByte` will become `uint80(ixFirstContentByte - 1)`, i.e. the computed end of the contents octets will be before the start. This will lead to invalid pointers being generated by `NodePtr.getPtr()`; invalid pointers can cause `X509Verifier` to traverse certificates incorrectly in `verifySignedX509`. In particular, because the `NodePtr.nextSiblingOf()` uses the last index to calculate the pointer to the next ASN.1 data value in a sequence, code such as `verifySignedX509()` that traverses the ASN.1 data will read the data incorrectly.

## Recommendation

The developers should change `readNodeLength()` to construct the `ixLastContentByte` as an exclusive index and then make all methods that reference the `ixf()` function to be consistent with the change.

**Comment by robertsdotpm** [comment]
Added a few changes to address this.

When the content field is empty the content start pointer will be set to zero. This won't conflict with other logic as the content start pointer must always be > 0 to be valid. This is true given that its always at least prefixed by a type field + [some form of] len field. So zero is reserved for that purpose. I have also changed the 'last content byte' pointer to now point to the end of the DER segment. This means it may point to the end of the length field(s) if no content portion is present or to a content byte. I've also added an appropriate method called content_len() that returns the expected value. 

Tests now check that return values are as expected for all methods. Including methods that check that traversal of successive fields with empty content portions work. There are checks for overflows and success for all methods. Hopefully I didn't miss anything. This code required a lot of fixes.
