### ISSUE TITLE
str.strip() leads to data corruption

### ISSUE THREAD

**Issue by thomasknauth** [PufferFinance/rave#25]
str.strip() has the wrong semantics here since it will strip more than just the leading '0x'. For example, `'0x0012'.strip('0x')` will turn into `12` which in the context of certificates etc. is basically a data corruption. Recent Python versions have `str.removeprefix()` which is likely a better choice here.

https://github.com/PufferFinance/rave/blob/664d7240a589cb21236557fb85752003923af894/test/scripts/runReadCached.py#L22

**Comment by robertsdotpm** [comment]
Good catch. this test has been failing for a while and I haven't had chance to fix it. So that's a very good start.

**Comment by robertsdotpm** [comment]
You were right. I made some changes to fix this issue. Thank you for finding this.
