### ISSUE TITLE
CacheTheX509s test does not finish

### ISSUE THREAD

**Issue by thomasknauth** [PufferFinance/rave#26]
https://github.com/PufferFinance/rave/blob/664d7240a589cb21236557fb85752003923af894/test/RAVE.t.sol#L164C1-L164C54

Not sure about the intention behind the busy loop, but it also leads to the `CacheTheX509s` test (`forge test --ffi --match-contract CacheTheX509s`) not finishing in a reasonable amount of time (stopped after 5min). The test happens to be part of the CI test suite.

**Comment by robertsdotpm** [comment]
I disabled some test modes and restricted some cases in fuzzing that lead to invalid results. There were a few issues with the x509 generation steps and weird race conditions.
